version: '2.2'

services:
  nginx:
    image: nginx:1.17.3
    container_name: nginx
    labels:
      "co.elastic.logs/module": "nginx"
      "co.elastic.logs/fileset.stdout": "access"
      "co.elastic.logs/fileset.stderr": "error"
      "co.elastic.metrics/module": "nginx"
      "co.elastic.metrics/hosts": "nginx:8081"
      "co.elastic.metrics/metricsets": "stubstatus"
    ports:
      - 8081:8081
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - elastic
  petclinic:
    image: docker.io/michaelhyatt/elastic-k8s-o11y-workshop-petclinic:1.25.0
    container_name: petclinic
    labels:
      "co.elastic.metrics/module": "prometheus"
      "co.elastic.metrics/hosts": "$${data.host}:$${data.port}"
      "co.elastic.metrics/metrics_path": "/metrics/prometheus"
      "co.elastic.metrics/period": "1m"
    environment:
      ELASTIC_APM_SERVER_URLS: "http://apm-server:8200"
      ELASTIC_APM_SERVER_URLS_FOR_RUM: "http://localhost:8200"
      ELASTIC_APM_SECRET_TOKEN: ""
      ELASTIC_APM_SERVICE_NAME: "spring-petclinic-monolith"
      ELASTIC_APM_APPLICATION_PACKAGES: "org.springframework.samples"
      ELASTIC_APM_ENABLE_LOG_CORRELATION: "true"
      ELASTIC_APM_CAPTURE_JMX_METRICS: >
        object_name[java.lang:type=GarbageCollector,name=*] attribute[CollectionCount:metric_name=collection_count] attribute[CollectionTime:metric_name=collection_time],
        object_name[java.lang:type=Memory] attribute[HeapMemoryUsage:metric_name=heap]
      JAVA_OPTS: >
        -Xms100m
        -Xmx256m
        -Dspring.profiles.active=mysql
        -Ddatabase=mysql
        -Dspring.datasource.username=root
        -Dspring.datasource.password=petclinic
        -Dspring.datasource.initialization-mode=always
        -Dspring.datasource.url=jdbc:mysql://mysql:3306/petclinic?autoReconnect=true&useSSL=false
        -XX:+StartAttachListener
    ports:
      - 8080:8080
    networks:
      - elastic

  mysql:
    image: mysql:5.7.27
    container_name: mysql
    labels:
      "co.elastic.logs/module": "mysql"
      "co.elastic.metrics/module": "mysql"
      "co.elastic.metrics/hosts": "root:petclinic@tcp($${data.host}:3306)/"
    environment:
      MYSQL_ROOT_PASSWORD: petclinic
      MYSQL_DATABASE: petclinic
    ports:
      - 3306
    networks:
      - elastic

networks:
  elastic:
    name: elastic
    driver: bridge
